tonic::include_proto!("izdu");

pub use image_processor_server::ImageProcessorServer;

pub mod server {
    use crate::image_processor;
    use crate::image_processor::image_slicer;
    use crate::image_processor::watermark;
    use bytes::Bytes;
    use image::ImageBuffer;
    use std::pin::Pin;
    use tokio::sync::mpsc;
    use tokio_stream::wrappers::ReceiverStream;
    use tokio_stream::StreamExt;
    use tonic::{Request, Response, Status, Streaming};

    // Proto types — generated by tonic from izdu.proto
    use super::batch_response::Result as ProtoBatchResult;
    use super::image_processor_server::ImageProcessor;
    use super::image_source::Source as ProtoSource;
    use super::operation::Op as ProtoOp;
    use super::{
        BatchRequest as ProtoBatchRequest, BatchResponse as ProtoBatchResponse,
        BatchSliceResult as ProtoBatchSliceResult, ImageSource as ProtoImageSource,
        ResizeRequest as ProtoResizeRequest, ResizeResponse as ProtoResizeResponse,
        SliceRequest as ProtoSliceRequest, SliceResponse as ProtoSliceResponse,
        WatermarkConfig as ProtoWatermarkConfig, WatermarkRequest as ProtoWatermarkRequest,
        WatermarkResponse as ProtoWatermarkResponse,
    };

    // Convert proto ImageSource to our internal ImageSource
    fn proto_to_image_source(src: Option<ProtoImageSource>) -> crate::image_processor::ImageSource {
        match src {
            Some(s) => match s.source {
                Some(ProtoSource::Url(u)) => crate::image_processor::ImageSource::Url(u),
                Some(ProtoSource::Data(d)) => crate::image_processor::ImageSource::Binary(d),
                Some(ProtoSource::Base64(b)) => crate::image_processor::ImageSource::Base64(b),
                None => crate::image_processor::ImageSource::Binary(vec![]),
            },
            None => crate::image_processor::ImageSource::Binary(vec![]),
        }
    }

    fn encode_png(img: ImageBuffer<image::Rgba<u8>, Vec<u8>>) -> Result<Bytes, String> {
        let mut buf = Vec::new();
        img.write_to(&mut std::io::Cursor::new(&mut buf), image::ImageFormat::Png)
            .map_err(|e| format!("PNG encode error: {}", e))?;
        Ok(Bytes::from(buf))
    }

    fn decode_wm_config(wm: Option<ProtoWatermarkConfig>) -> (String, u32) {
        wm.map(|w| (w.text, w.transparency))
            .unwrap_or_else(|| ("IZDU-Slicer".to_string(), 30))
    }

    pub struct GrpcServer;

    impl Default for GrpcServer {
        fn default() -> Self {
            Self
        }
    }

    #[tonic::async_trait]
    impl ImageProcessor for GrpcServer {
        type SliceStream =
            Pin<Box<dyn tokio_stream::Stream<Item = Result<ProtoSliceResponse, Status>> + Send>>;
        type ProcessBatchStream =
            Pin<Box<dyn tokio_stream::Stream<Item = Result<ProtoBatchResponse, Status>> + Send>>;

        async fn slice(
            &self,
            request: Request<ProtoSliceRequest>,
        ) -> Result<Response<<Self as ImageProcessor>::SliceStream>, Status> {
            let req = request.into_inner();
            let source = proto_to_image_source(req.source);
            let scale = if req.scale == 0 { 300 } else { req.scale };

            let img = image_processor::load_image(source)
                .await
                .map_err(|e| Status::internal(e.to_string()))?;

            let (wm_text, wm_alpha) = decode_wm_config(req.watermark);
            let dim = image_slicer::get_single_image_dimensions(&img);

            let mut sliced = if wm_text.is_empty() {
                image_slicer::slice_images_view(img, &dim)
            } else {
                let wm = watermark::create_watermark(&wm_text, (dim.width, dim.height));
                let mut out = image_slicer::slice_images_view(img, &dim);
                for s in &mut out {
                    *s = watermark::add_watermark(s.clone(), &wm, wm_alpha as f32 / 100.0);
                }
                out
            };

            if scale > 0 && scale < dim.smallest {
                sliced = image_slicer::resize(sliced, scale);
            }

            let (tx, rx) = mpsc::channel(4);
            tokio::spawn(async move {
                for (i, img) in sliced.into_iter().enumerate() {
                    let resp = match encode_png(img) {
                        Ok(data) => Ok(ProtoSliceResponse {
                            index: i as u32,
                            data: data.to_vec(),
                            error: String::new(),
                        }),
                        Err(e) => Ok(ProtoSliceResponse {
                            index: i as u32,
                            data: vec![],
                            error: e,
                        }),
                    };
                    let _ = tx.send(resp).await;
                }
            });

            Ok(Response::new(Box::pin(ReceiverStream::new(rx))))
        }

        async fn watermark(
            &self,
            request: Request<ProtoWatermarkRequest>,
        ) -> Result<Response<ProtoWatermarkResponse>, Status> {
            let req = request.into_inner();
            let source = proto_to_image_source(req.source);
            let (text, alpha) = decode_wm_config(req.watermark);

            let img = image_processor::load_image(source)
                .await
                .map_err(|e| Status::internal(e.to_string()))?;

            let (w, h) = (img.width(), img.height());
            let wm = watermark::create_watermark(&text, (w, h));
            let watermarked = watermark::add_watermark(img.to_rgba8(), &wm, alpha as f32 / 100.0);
            let data = encode_png(watermarked).map_err(|e| Status::internal(e))?;

            Ok(Response::new(ProtoWatermarkResponse {
                data: data.to_vec(),
                error: String::new(),
            }))
        }

        async fn resize(
            &self,
            request: Request<ProtoResizeRequest>,
        ) -> Result<Response<ProtoResizeResponse>, Status> {
            let req = request.into_inner();
            let source = proto_to_image_source(req.source);

            let (width, height, ar) = req
                .resize
                .map(|r| {
                    let ar = if r.aspect_ratio.is_empty() {
                        "preserve".to_string()
                    } else {
                        r.aspect_ratio
                    };
                    (Some(r.width), Some(r.height), ar)
                })
                .unwrap_or((None, None, "preserve".to_string()));

            if ar == "ignore" && (width.is_none() || height.is_none()) {
                return Err(Status::invalid_argument(
                    "aspect_ratio=ignore requires width and height",
                ));
            }

            let img = image_processor::load_image(source)
                .await
                .map_err(|e| Status::internal(e.to_string()))?;

            let resized = image_slicer::resize_single(img, width, height, &ar);
            let data = encode_png(resized.to_rgba8()).map_err(|e| Status::internal(e))?;

            Ok(Response::new(ProtoResizeResponse {
                data: data.to_vec(),
                error: String::new(),
            }))
        }

        async fn process_batch(
            &self,
            request: Request<Streaming<ProtoBatchRequest>>,
        ) -> Result<Response<<Self as ImageProcessor>::ProcessBatchStream>, Status> {
            let mut stream = request.into_inner();
            let (tx, rx) = mpsc::channel(128);

            tokio::spawn(async move {
                while let Some(req) = stream.next().await {
                    let req = match req {
                        Ok(r) => r,
                        Err(e) => {
                            let _ = tx.send(Err(Status::internal(e.to_string()))).await;
                            continue;
                        }
                    };

                    let rid = req.request_id.clone();
                    let resp: ProtoBatchResponse = match req.operation {
                        Some(operation) => match operation.op {
                            Some(ProtoOp::Slice(s)) => {
                                let source = proto_to_image_source(s.source);
                                let scale = if s.scale == 0 { 300 } else { s.scale };
                                let (wm_text, wm_alpha) = decode_wm_config(s.watermark);
                                match image_processor::load_image(source).await {
                                    Ok(img) => {
                                        let dim = image_slicer::get_single_image_dimensions(&img);
                                        let mut sliced = image_slicer::slice_images_view(img, &dim);
                                        if !wm_text.is_empty() {
                                            let wm = watermark::create_watermark(
                                                &wm_text,
                                                (dim.width, dim.height),
                                            );
                                            for slice_img in &mut sliced {
                                                *slice_img = watermark::add_watermark(
                                                    slice_img.clone(),
                                                    &wm,
                                                    wm_alpha as f32 / 100.0,
                                                );
                                            }
                                        }
                                        if scale > 0 && scale < dim.smallest {
                                            sliced = image_slicer::resize(sliced, scale);
                                        }
                                        let slices: Vec<_> = sliced
                                            .into_iter()
                                            .enumerate()
                                            .map(|(i, img)| ProtoSliceResponse {
                                                index: i as u32,
                                                data: encode_png(img)
                                                    .map(|d| d.to_vec())
                                                    .unwrap_or_default(),
                                                error: String::new(),
                                            })
                                            .collect();
                                        ProtoBatchResponse {
                                            request_id: rid,
                                            error: String::new(),
                                            result: Some(ProtoBatchResult::Slice(
                                                ProtoBatchSliceResult { slices },
                                            )),
                                        }
                                    }
                                    Err(e) => ProtoBatchResponse {
                                        request_id: rid,
                                        error: e.to_string(),
                                        result: None,
                                    },
                                }
                            }
                            Some(ProtoOp::Watermark(wm_op)) => {
                                let source = proto_to_image_source(wm_op.source);
                                let (text, alpha) = decode_wm_config(wm_op.watermark);
                                match image_processor::load_image(source).await {
                                    Ok(img) => {
                                        let (w, h) = (img.width(), img.height());
                                        let wm = watermark::create_watermark(&text, (w, h));
                                        let watermarked = watermark::add_watermark(
                                            img.to_rgba8(),
                                            &wm,
                                            alpha as f32 / 100.0,
                                        );
                                        match encode_png(watermarked) {
                                            Ok(data) => ProtoBatchResponse {
                                                request_id: rid,
                                                error: String::new(),
                                                result: Some(ProtoBatchResult::Watermark(
                                                    ProtoWatermarkResponse {
                                                        data: data.to_vec(),
                                                        error: String::new(),
                                                    },
                                                )),
                                            },
                                            Err(e) => ProtoBatchResponse {
                                                request_id: rid,
                                                error: e,
                                                result: None,
                                            },
                                        }
                                    }
                                    Err(e) => ProtoBatchResponse {
                                        request_id: rid,
                                        error: e.to_string(),
                                        result: None,
                                    },
                                }
                            }
                            Some(ProtoOp::Resize(rs_op)) => {
                                let source = proto_to_image_source(rs_op.source);
                                let (width, height, ar) = rs_op
                                    .resize
                                    .map(|r| {
                                        let ar = if r.aspect_ratio.is_empty() {
                                            "preserve".to_string()
                                        } else {
                                            r.aspect_ratio
                                        };
                                        (Some(r.width), Some(r.height), ar)
                                    })
                                    .unwrap_or((None, None, "preserve".to_string()));
                                if ar == "ignore" && (width.is_none() || height.is_none()) {
                                    ProtoBatchResponse {
                                        request_id: rid,
                                        error: "aspect_ratio=ignore requires width and height"
                                            .into(),
                                        result: None,
                                    }
                                } else {
                                    match image_processor::load_image(source).await {
                                        Ok(img) => {
                                            let resized = image_slicer::resize_single(
                                                img, width, height, &ar,
                                            );
                                            match encode_png(resized.to_rgba8()) {
                                                Ok(data) => ProtoBatchResponse {
                                                    request_id: rid,
                                                    error: String::new(),
                                                    result: Some(ProtoBatchResult::Resize(
                                                        ProtoResizeResponse {
                                                            data: data.to_vec(),
                                                            error: String::new(),
                                                        },
                                                    )),
                                                },
                                                Err(e) => ProtoBatchResponse {
                                                    request_id: rid,
                                                    error: e,
                                                    result: None,
                                                },
                                            }
                                        }
                                        Err(e) => ProtoBatchResponse {
                                            request_id: rid,
                                            error: e.to_string(),
                                            result: None,
                                        },
                                    }
                                }
                            }
                            None => ProtoBatchResponse {
                                request_id: rid,
                                error: "no operation".into(),
                                result: None,
                            },
                        },
                        None => ProtoBatchResponse {
                            request_id: rid,
                            error: "no operation".into(),
                            result: None,
                        },
                    };
                    let _ = tx.send(Ok(resp)).await;
                }
            });

            Ok(Response::new(Box::pin(ReceiverStream::new(rx))))
        }
    }
}
